name = "BinarizeDynamics"
uuid = "1e873919-6d6a-4632-9c4c-35456f4d0124"
version = "0.1.0"
authors = ["Project Maintainer"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
FASTX = "c2308a5c-f048-11e8-3e8a-31650f418d12"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
BinarizeDynamicsMakieExt = "Makie"

[compat]
CSV = "0.10.15"
CairoMakie = "0.15.8"
DataFrames = "1.8.1"
DocumenterTools = "0.1.21"
FASTX = "2.1.7"
LinearAlgebra = "1.10.0"
Makie = "0.24.8"
Random = "1.10.0"
Statistics = "1.10.0"
Test = "1.10.0"
