name = "BinarizeDynamics"
uuid = "1e873919-6d6a-4632-9c4c-35456f4d0124"
version = "0.1.0"
authors = ["Project Maintainer"]

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
CairoMakie = "0.15.8"
LinearAlgebra = "1.12.0"
LoopVectorization = "0.12.173"
Makie = "0.24.8"
Statistics = "1.11.1"
Test = "1.11.0"
